# Generated by Django 3.2.3 on 2021-05-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210517_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='imageUri',
            field=models.BinaryField(editable=True),
        ),
    ]
