# Generated by Django 3.2.3 on 2021-05-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210518_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dataType',
            field=models.CharField(default='image', max_length=50),
        ),
    ]
