# Generated by Django 3.2.3 on 2021-05-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dataType',
            field=models.CharField(max_length=50),
        ),
    ]
