# Generated by Django 3.2.3 on 2021-05-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_datatype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dataType',
            new_name='imageType',
        ),
    ]
