# Generated by Django 3.2.3 on 2021-05-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_rename_name_post_currentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='currentName',
            field=models.CharField(max_length=32),
        ),
    ]
